export const words = [
  { word: "Halcyon", definition: "Denoting a period of time that was idyllically happy and peaceful.", example: "They reminisced about the halcyon days of their youth." },
  { word: "Euphoria", definition: "A feeling or state of intense excitement and happiness.", example: "Winning the championship brought a wave of euphoria." },
  { word: "Ineffable", definition: "Too great or extreme to be expressed in words.", example: "The ineffable beauty of the mountains left us speechless." },
  { word: "Quintessential", definition: "Representing the most perfect example of something.", example: "She is the quintessential leader — confident and kind." },
  { word: "Solitude", definition: "The state of being alone.", example: "He enjoyed the solitude of the early morning hours." },
  { word: "Labyrinth", definition: "A complicated irregular network of passages or paths.", example: "The old city was a labyrinth of narrow alleys." },
  { word: "Effervescent", definition: "Vivacious and enthusiastic.", example: "Her effervescent personality lit up the room." },
  { word: "Petrichor", definition: "A pleasant smell that frequently accompanies the first rain.", example: "The petrichor after the storm was refreshing." },
  { word: "Cacophony", definition: "A harsh discordant mixture of sounds.", example: "The cacophony of the city kept him awake." },
  { word: "Nostalgia", definition: "A sentimental longing for the past.", example: "Old photos filled her with nostalgia." },
  { word: "Mellifluous", definition: "A sound that is sweet and smooth.", example: "His mellifluous voice captivated the audience." },
  { word: "Zephyr", definition: "A soft gentle breeze.", example: "A warm zephyr brushed across her face." },
  { word: "Eloquent", definition: "Fluent or persuasive in speaking or writing.", example: "Her speech was powerful and eloquent." },
  { word: "Resilience", definition: "The capacity to recover quickly from difficulties.", example: "Children have an amazing resilience." },
  { word: "Incandescent", definition: "Emitting light as a result of being heated.", example: "The incandescent bulb flickered warmly." },
  { word: "Aesthetic", definition: "Concerned with beauty or the appreciation of beauty.", example: "The painting has great aesthetic value." },
  { word: "Solace", definition: "Comfort in a time of distress.", example: "She found solace in reading poetry." },
  { word: "Aurora", definition: "A natural light display in the sky.", example: "We watched the aurora dance across the northern sky." },
  { word: "Ethereal", definition: "Extremely delicate and light in a way that seems not of this world.", example: "Her dress had an ethereal glow." },
  { word: "Reverie", definition: "A state of being pleasantly lost in one's thoughts.", example: "He was lost in a reverie during the lecture." },
  { word: "Sonorous", definition: "Imposingly deep and full sound.", example: "His sonorous voice echoed through the hall." },
  { word: "Tranquil", definition: "Free from disturbance; calm.", example: "The tranquil lake was perfect for meditation." },
  { word: "Lustrous", definition: "Having a gentle sheen or soft glow.", example: "Her hair was dark and lustrous." },
  { word: "Epiphany", definition: "A moment of sudden revelation or insight.", example: "He had an epiphany about his life's purpose." },
  { word: "Vellichor", definition: "The strange wistfulness of used bookstores.", example: "The vellichor of the old shop was enchanting." },
  { word: "Panacea", definition: "A solution or remedy for all problems.", example: "There is no panacea for the challenges of life." },
  { word: "Seraphic", definition: "Characteristic of or resembling an angelic being.", example: "Her seraphic smile calmed the room." },
  { word: "Ambrosial", definition: "Exceptionally pleasing to taste or smell.", example: "The ambrosial aroma of the meal filled the air." },
  { word: "Opulent", definition: "Ostentatiously rich and luxurious.", example: "The palace was an opulent display of wealth." },
  { word: "Epistolary", definition: "Relating to the writing of letters.", example: "They had an epistolary relationship over many years." },
  { word: "Liminal", definition: "Relating to a transitional or initial stage.", example: "She stood in a liminal space between decisions." },
  { word: "Candescent", definition: "Glowing from heat.", example: "The candescent coals glowed red-hot." },
  { word: "Pulchritude", definition: "Beauty.", example: "The pulchritude of the landscape was breathtaking." },
  { word: "Iridescent", definition: "Showing luminous colors that seem to change.", example: "The soap bubble was iridescent in the sunlight." },
  { word: "Evanescent", definition: "Quickly fading or disappearing.", example: "Her joy was evanescent, gone in a moment." },
  { word: "Susurrus", definition: "Whispering or rustling sound.", example: "The susurrus of leaves soothed him to sleep." },
  { word: "Numinous", definition: "Having a strong religious or spiritual quality.", example: "The cathedral had a numinous atmosphere." },
  { word: "Catharsis", definition: "The process of releasing strong emotions.", example: "Writing was a form of catharsis for her." },
  { word: "Eunoia", definition: "Beautiful thinking; a well mind.", example: "Her kindness was rooted in deep eunoia." },
  { word: "Komorebi", definition: "Sunlight filtering through trees.", example: "The komorebi made the forest magical." },
  { word: "Hiraeth", definition: "A longing for a home you can’t return to.", example: "He felt hiraeth for his childhood village." },
  { word: "Plenitude", definition: "An abundance.", example: "There was a plenitude of food on the table." },
  { word: "Sonder", definition: "The realization that each passerby has a complex life.", example: "Sonder struck him as he walked through the crowd." },
  { word: "Alpenglow", definition: "The rosy light of the setting or rising sun on mountains.", example: "The peaks glowed with alpenglow." },
  { word: "Calligraphy", definition: "Decorative handwriting or handwritten lettering.", example: "She studied ancient calligraphy styles." },
  { word: "Equanimity", definition: "Mental calmness, especially in difficult situations.", example: "He faced the storm with equanimity." },
  { word: "Zeal", definition: "Great energy or enthusiasm.", example: "She tackled her tasks with zeal." },
  { word: "Metanoia", definition: "The journey of changing one’s mind, heart, or self.", example: "His metanoia led him to a new path." },
  { word: "Philomath", definition: "A lover of learning.", example: "Being a philomath, he read every day." },
];
